config/routes.rb
Hotels::Application.routes.draw do
  resources :users
  resources :admins
  resources :sessions, only: [:new, :create, :destroy]
  resources :hotels
  resources :rates, only: [:create]
  resources :admins_sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/home',    to: 'static_pages#home', via: 'get' 
  match '/rating',  to: 'hotels#index',  via: 'get'
  match '/signup',  to: 'users#new',     via: 'get'
  match '/signin',  to: 'sessions#new',  via: 'get'
  match '/signout', to: 'sessions#destroy',  via: 'delete'
  match '/admin',   to: 'admins_sessions#new', via: 'get'
  match '/admin_dashboard', to: 'admins#home', via: 'get'
  match '/admin_signout', to: 'admins_sessions#destroy', via: 'delete'
  match 'admin/hotels', to: 'admins#hotels', via: 'get' 
  match 'admin/hotels', to: 'admins#update', via: 'patch'
   resources :admins do
    resources :hotels
  end

  

end

app/views/admins/edit.html.erb
edit.html.erb

app/views/admins/home.html.erb
<div class="row span4">
  <h1> Admin Panel </h1>  
  <% if admin_signed_in? %>
    <br> Hello, admin <br/>
    <%= link_to "Manage hotels", admin_hotels_path %>
    <%= link_to "End admin session", admin_signout_path, :method => :delete %>
    <%= link_to "Add user", signup_path, :method => :get %>
    <h4> Filter by name or email:</h4>

    <%= form_tag admin_dashboard_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
      </p>
    <% end %>
      <table class="Users table">
        <thead>
          <td><strong><%= sort_link "id" %></strong></td>
          <td><strong><%= sort_link "name" %></strong></td>
          <td><strong><%= sort_link "email" %></strong></td>
          <td><strong><%= sort_link "hotels" %></strong></td>
          <td><strong><%= sort_link "rates" %></strong></td>
          <td><strong>delete user</strong></td>
          <td><strogn>Edit user </strong></td>
        </thead>
        <% @users.each do |user| %>
          <%= render user %>
        <% end %>
      </table>  


  <% else %>
    <p> Admin Zone </p>  
    <div class="row">
      <div class="span6 offset3">
        <%= form_for(:admins_session, url: admins_sessions_path) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          <%= f.label :password %>
          <%= f.password_field :password %>
          <%= f.submit "Admin Sign in", class: "btn btn-large btn-primary" %>
        <% end %>
      </div>
    </div>

  <% end %>
</div>      

app/views/admins/hotels.html.erb
<div class="row span4">
  <h1> Admin Panel </h1>  
  <% if admin_signed_in? %>
    <br> Hello, admin <br/>
    <%= link_to "Manage users", admin_dashboard_path %>
    <%= link_to "End admin session", admin_signout_path, :method => :delete %>

    <h4> Filter by status:</h4>
    <%= form_tag admin_hotels_path, :method => 'get' do %>
      <p>
        <%= select_tag(:search, options_for_select([['approved', "approved"], ['rejected', 'rejected'], ['pending', 'pending'], [ 'All','']])  )%>
        <%= submit_tag "Search", :status => nil %>
      </p>
    <% end %>

    <table>
      <thead>
        <td><strong>Hotel id</strong> </td>
        <td><strong>Hotel name</strong> </td>
        <td><strong>Count of stars</strong> </td>
        <td><strong>Rating</strong> </td>
        <td><strong>Status</strong> </td>
        <td><strong>Current Status</strong> </td>
      </thead>
      <% @hotels.each do |hotel| %>
        <%= render hotel %>
      <% end %>
    </table> 
  <% else %>
    <p> Admin Zone </p>  
    <%= form_for(:admins_session, url: admins_sessions_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>
  <% end %>

</div>      