config/routes.rb
Hotels::Application.routes.draw do
  resources :users
  resources :admins
  resources :sessions, only: [:new, :create, :destroy]
  resources :hotels
  resources :rates, only: [:create]
  resources :admins_sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/home',    to: 'static_pages#home', via: 'get' 
  match '/rating',  to: 'hotels#index',  via: 'get'
  match '/signup',  to: 'users#new',     via: 'get'
  match '/signin',  to: 'sessions#new',  via: 'get'
  match '/signout', to: 'sessions#destroy',  via: 'delete'
  match '/admin',   to: 'admins_sessions#new', via: 'get'
  match '/admin_dashboard', to: 'admins#home', via: 'get'
  match '/admin_signout', to: 'admins_sessions#destroy', via: 'delete'
  match 'admin/hotels', to: 'admins#hotels', via: 'get' 
  match 'admin/hotels', to: 'admins#update', via: 'patch'
   resources :admins do
    resources :hotels
  end

  

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :rates, inverse_of: :hotel
  has_one :address
  default_scope -> { order 'rate_avg DESC, rates_count DESC'}
  before_save do 
    self.title = title.strip
  end 
  validates :title, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :stars, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 5  }
  validates :price, numericality: true

  def self.search(search)
    if search
      Hotel.where(['status LIKE ?', "%#{search}%"])
    else
      all
    end
  end


end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  before_action :signed_in_user, only: [:new, :create]

  def index
    @hotels = Hotel.where("status='approved'").search(params[:search])
  end

  def show
    @hotel = Hotel.find(params[:id])
    @rates = @hotel.rates.paginate(page: params[:page])
    @rate = @hotel.rates.build
  end

  def new
    @hotel = Hotel.new
    @address = @hotel.build_address
  end

  def update
    if params.has_key?(:status)
      hotel = Hotel.find(params[:id])
      hotel.update_attribute('status', params[:status]) 
      if params[:status] == "rejected" 
        UserMailer.reject_hotel(hotel).deliver
      elsif params[:status] == "approved"
        UserMailer.approve_hotel(hotel).deliver
      end     
      redirect_to(:back)
    end
  end

  def create
    @hotel = Hotel.new(hotel_params) 
    @hotel.user = current_user
    @address = @hotel.build_address(address_params)
    if @hotel.save && @address.save
      flash[:success] = "New hotel was added successfully"  
      redirect_to hotels_url
    else
      render 'new'
    end
  end


private

    def hotel_params
      params.require(:hotel).permit(:title, :stars, :breakfast, :description, :price, :photo)
    end

    def address_params
      params.require(:address).permit(:country, :city, :state, :street)
    end
    
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_hotel.html.erb
<% if admin_signed_in? && current_page?('/admin/hotels') %>
  	<tr>	
		<td><%= hotel.id %> </td>
		<td><%= hotel.title %></td>
		<td><%= hotel.stars %></td>
		<td><%= hotel.rate_avg %></td>
		<% if hotel.status == 'pending' %>
			<td><%= link_to 'approve', hotel_path(hotel, status: 'approved'), method: :put   %> / <%= link_to 'rejecte', hotel_path(hotel, status: 'rejected'), method: :put %></td>
		<% else %>
			<td></td>
		<% end %>
		<td><%= hotel.status %></td>

	</tr>	
  
<% else %>

	<li id="<%= hotel.id %>">
	  <span class="photo">
	  	<img src='<%= "#{hotel.photo_url}" %>' height='100' width='100'> 
	  </span>	
	  <span class="hotel">
	    <%= link_to hotel.title, hotel %>
	    <%= "*"*hotel.stars %>
	  </span>
	  <span class="content"><%= "Average of #{ pluralize(hotel.rates_count, "rate") }: #{ '%.1f' % hotel.rate_avg } / 5" %></span>
	</li>
<% end %>	

app/views/hotels/_hotels.html.erb
<li id="<%= hotel.id %>">
  <span class="hotel">
    <%= link_to hotel.title, hotel %>
    <%= "*"*hotel.stars %>
  </span>
  <span class="content"><%= "Score from #{ pluralize(hotel.rates_count, "review") }: #{ '%.1f' % hotel.rate_avg } / 5" %></span>
</li>

app/views/hotels/index.html.erb
<% provide(:title, 'Rating') %>
<h1>Rating</h1>


<ol class="hotels">

  <span class="hotel">
    <%= link_to "Add new hotel", new_hotel_path %>
  </span>

  <% @hotels.each do |hotel| %>
    <%= render hotel %>
  <% end %>
</ol>

app/views/hotels/new.html.erb
<% provide(:title, 'Add new Hotel') %>
<h1>Add new Hotel</h1>

<div class="row">
  <div class="span6 offset3">
	<%= form_for(@hotel) do |f| %>
	    <%= render 'shared/error_messages', object: f.object %>

	    <%= f.label :title %>
	    <%= f.text_field :title %>

	    <%= f.label :stars %>
	    <%= f.select :stars, 1..5 %>

      <%= f.label :photo %>
      <%= f.file_field :photo %>

      <%= f.label :breakfast %> 
      <%= f.check_box :breakfast %>

      <%= f.label :description %> 
      <%= f.text_area :description %>

      <%= f.label :price %>
	    <%= f.text_field :price %>

	    <%= fields_for @address do |fa| %>
        <%=fa.label :country %>
        <%=fa.text_field :country %>
        <%=fa.label :city %>
        <%=fa.text_field :city %>
        <%=fa.label :state %>
        <%=fa.text_field :state %>
        <%=fa.label :street %>
        <%=fa.text_field :street %>
      <% end %>
	  <%= f.submit "Save", class: "btn btn-large btn-primary" %>
	<% end %>
  </div>
</div>

app/views/hotels/show.html.erb
<% provide(:title, 'Hotel details') %>
<h1><%= @hotel.title + "*"*@hotel.stars %></h1>

  <div class="row">
    <aside class="span4">
      <section>
        <span> <img src='<%= "#{@hotel.photo_url}" %>' height='100' width='100'> </span>
        <span class="content">
         	<b>Average</b><%= " of #{ pluralize(@hotel.rates.count, "rate") }: #{ '%.1f' % @hotel.rate_avg } / 5" %>
        </span>
        <span class="content"><b>Status:</b><%= " #{@hotel.status}" %></span>
        <% if admin_signed_in?%>  
          <% if @hotel.status == 'pending' %>
            <span><%= link_to 'approve', hotel_path(@hotel, status: 'approved'), method: :put   %> / <%= link_to 'rejecte', hotel_path(@hotel, status: 'rejected'), method: :put %>  </span>
          <% else %>
              <span></span>
          <% end %>
        <% end %>  
        <span class="content"><b>Breakfast included:</b><%= " #{(@hotel.breakfast == true) ? 'yes':'no'}" %></span>
        <span class="content"><b>Room description:</b><%= " #{@hotel.description}" %></span>
        <span class="content"><b>Room price:</b><%= " #{@hotel.price}" %></span>
        <span class="content">
      	  <b>Address:</b><%= " #{@hotel.address.country} #{@hotel.address.state}, #{@hotel.address.city}, #{@hotel.address.street}" %>
        </span>
      </section>

      <section>
        <% if signed_in? %>
        <%= form_for(@rate) do |f| %>
          <div class="field">
          	<%= render 'shared/error_messages', object: f.object %>
          	<%= f.label :rate %>
        	  <%= f.select :rate, 1..5 %>
            <%= f.text_area :comment, placeholder: "Leave your comment..." %>
            <%= f.hidden_field :hotel_id, value: @hotel.id %>
          </div>
          <%= f.submit "Rate", class: "btn btn-large btn-primary" %>
        <% end %>
        <% else %>
           <%= link_to "Please sign in to rate", signin_path %>  
        <% end %>

      </section>

    </aside>
    <div class="span8">
      <% if @rates.any? %>
        <h3>Rates</h3>
        <ol class="rates">
          <% @rates.each do |rate| %>
            <li id="<%= rate.id %>">
              <span class="user">
                <%= rate.user.name %>
              </span>
              <span class="content"><%= "Rate: #{rate.rate} / 5" %></span>
              <span class="content"><%= rate.comment %></span>
              <span class="timestamp">
                Rated <%= time_ago_in_words(rate.created_at) %> ago.
              </span>
            </li>
          <% end %>
        </ol>
        <%= will_paginate @rates %>
      <% else %>
        <h3>No rates</h3> 
      <% end %>
    </div>
  </div>