config/routes.rb
Hotels::Application.routes.draw do
  resources :users
  resources :admins
  resources :sessions, only: [:new, :create, :destroy]
  resources :hotels
  resources :rates, only: [:create]
  resources :admins_sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/home',    to: 'static_pages#home', via: 'get' 
  match '/rating',  to: 'hotels#index',  via: 'get'
  match '/signup',  to: 'users#new',     via: 'get'
  match '/signin',  to: 'sessions#new',  via: 'get'
  match '/signout', to: 'sessions#destroy',  via: 'delete'
  match '/admin',   to: 'admins_sessions#new', via: 'get'
  match '/admin_dashboard', to: 'admins#home', via: 'get'
  match '/admin_signout', to: 'admins_sessions#destroy', via: 'delete'
  match 'admin/hotels', to: 'admins#hotels', via: 'get' 
  match 'admin/hotels', to: 'admins#update', via: 'patch'
   resources :admins do
    resources :hotels
  end

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><a href="github.com/akulinind">Link to github</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Hotels!", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Rating", rating_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Edit profile", edit_user_path(current_user)%></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            <li><%= link_to "Add Hotel", new_hotel_path %></li>
          <% else %>
            <li><%= link_to "Sign in / Sign up", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>